import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Signin from './signin';
import { useSession, signIn, signOut, getCsrfToken } from 'next-auth/react'

export default function Home({ csrfToken }) {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
        </div>
        <div className={styles.center}>
          {!session ? <>
            <Image
              className='stupid-smug'
              src="/home.png"
              alt="13"
              width={200}
              height={200}
              priority
            />
          <div className={styles.thirteen}>
            <Signin {...csrfToken}/>
          </div>
          </> : <>
          <button onClick={() => signOut()}>logout</button>
          </>}
        </div>
        <div className={styles.grid}>
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps(context) {
  return {
    props: {
      csrfToken: await getCsrfToken(context),
    },
  }
}